In [1]:
import numpy as np
import matplotlib.pyplot as plt

# Иницилизация

In [5]:
a,b = 0,1
n = 100
t = np.linspace(a,b,n)
s = np.linspace(a,b,n)
x = np.linspace(a,b,n)
alpha = 1e-6
right_side = np.full(n,np.NAN)
left_side = np.full((n,n),np.NAN)
real_one = np.full(n,np.NAN)
A = np.ones(n)
A[0],A[n - 1] = 0.5,0.5
h = (b - a) / (n - 1)

In [6]:
for i in range(n):
    real_one[i] = np.sin(x[i])

In [7]:
real_one

array([0.        , 0.01010084, 0.02020065, 0.03029839, 0.04039305,
       0.05048358, 0.06056897, 0.07064817, 0.08072016, 0.09078392,
       0.10083842, 0.11088263, 0.12091552, 0.13093608, 0.14094328,
       0.1509361 , 0.16091352, 0.17087452, 0.18081808, 0.1907432 ,
       0.20064886, 0.21053404, 0.22039774, 0.23023896, 0.24005668,
       0.24984992, 0.25961766, 0.26935891, 0.27907268, 0.28875797,
       0.2984138 , 0.30803919, 0.31763315, 0.3271947 , 0.33672286,
       0.34621667, 0.35567516, 0.36509735, 0.3744823 , 0.38382904,
       0.39313661, 0.40240408, 0.41163048, 0.42081489, 0.42995636,
       0.43905397, 0.44810678, 0.45711386, 0.46607431, 0.47498721,
       0.48385164, 0.49266671, 0.5014315 , 0.51014514, 0.51880673,
       0.52741539, 0.53597023, 0.54447039, 0.55291499, 0.56130318,
       0.56963411, 0.57790691, 0.58612075, 0.59427479, 0.60236819,
       0.61040014, 0.6183698 , 0.62627638, 0.63411905, 0.64189703,
       0.64960951, 0.65725572, 0.66483486, 0.67234618, 0.67978

In [8]:
A

array([0.5, 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. ,
       1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. ,
       1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. ,
       1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. ,
       1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. ,
       1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. ,
       1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. ,
       1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 0.5])

In [9]:
left_side

array([[nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       ...,
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan]])

In [10]:
right_side

array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan])

Симетризованное ядро интегрального уравнения

In [11]:
def G_star_ts(t: float,s: float):
    if s > t:
        return (1 / (4 * (-np.exp(4) + 2 * np.exp(2) - 1))) * (np.exp(2 + t - s) * s - np.exp(2 + t - s) * t + np.exp(4 - t - s) * s + np.exp(4 - t - s) * t + np.exp(2 - t + s) * s - np.exp(2 - t + s) * t + np.exp(s + t) * s + np.exp(s + t) * t - np.exp(2 + s + t) * s - np.exp(2 + s + t) * t - np.exp(s - t) * s + np.exp(s - t) * t - np.exp(t + 4 - s) * s + np.exp(t + 4 - s) * t - np.exp(2 - t - s) * s - np.exp(2 - t - s) * t - np.exp(2 + t - s) + np.exp(4 - t - s) - 3 * np.exp(2 - t + s) - np.exp(s + t) + 3 * np.exp(2 + s + t) + np.exp(s - t) - np.exp(t + 4 - s) + np.exp(2 - t - s))
    else:
        return (1 / (4 * (np.exp(4) - 2 * np.exp(2) + 1))) * (np.exp(2 + t - s) * s - np.exp(2 + t - s) * t - np.exp(4 - t - s) * s - np.exp(4 - t - s) * t + np.exp(2 - t + s) * s - np.exp(2 - t + s) * t - np.exp(s + t) * s - np.exp(s + t) * t + np.exp(2 + s + t) * s + np.exp(2 + s + t) * t - np.exp(4 - t + s) * s + np.exp(4 - t + s) * t - np.exp(t - s) * s + np.exp(t - s) * t + np.exp(2 - t - s) * s + np.exp(2 - t - s) * t + 3 * np.exp(2 + t - s) - np.exp(4 - t - s) + np.exp(2 - t + s) + np.exp(s + t) - 3 * np.exp(2 + s + t) + np.exp(4 - t + s) - np.exp(t - s) - np.exp(2 - t - s))

Правая часть (как в первой лабораторной)

In [1]:
def y_star(t: float):
    return (1 / (4 * (np.exp(4) - 2 * np.exp(2) + 1))) * (np.sin(t) * np.exp(4) + np.sin(1) * t * np.exp(3 + t) + np.sin(1) * t * np.exp(3 - t) - np.sin(1) * t * np.exp(1 + t) - np.sin(1) * t * np.exp(1 - t) - np.sin(t) * 2 * np.exp(2) - np.sin(1) * 2 * np.exp(3 + t) + np.sin(1) * 2 * np.exp(3 - t) + np.sin(t))

## Ход основного алгоритма

In [3]:
for i in range(n):
    right_side[i] = y_star(t[i])
    

NameError: name 'n' is not defined

In [ ]:
for i in range(n):
    for j in range(n):
        left_side[i,j] = h * A[j] * G_star_ts(t[i],s[j])

In [ ]:
def asd():
    return (np.sin(1) * (1 + t) * np.exp(-t+1) + np.sin(1) * (4 * np.exp(2) * t - 2 * np.exp(4) * t + t * np.exp(1+t) - t * np.exp(3 - t) - t * np.exp(t + 3) - 2 * t - np.exp(1 + t) - 3 * np.exp(3 - t) + 3 * np.exp(t + 3))) / (-2 * np.exp(4) + 4 * np.exp(2) - 2)